from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy

from . import views


app_name = "operations"

urlpatterns = [
    path("", views.public_page, {"page": "home"}, name="home"),
    path("services/", views.public_page, {"page": "services"}, name="services"),
    path("projects/", views.public_page, {"page": "projects"}, name="projects"),
    path("process/", views.public_page, {"page": "process"}, name="process"),
    path("contact/", views.public_page, {"page": "contact"}, name="contact"),
    path("accounts/login/", views.GrandCoastLoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(next_page=reverse_lazy("operations:login")), name="logout"),
    path("accounts/delete/", views.account_delete, name="account-delete"),
    path("accounts/password/change/", views.GrandCoastPasswordChangeView.as_view(), name="password-change"),
    path("accounts/password/reset/", views.PublicPasswordResetView.as_view(), name="password-reset"),
    path("accounts/password/reset/done/", views.PublicPasswordResetDoneView.as_view(), name="password-reset-done"),
    path("accounts/password/reset/confirm/<uidb64>/<token>/", views.PublicPasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("accounts/password/reset/complete/", views.PublicPasswordResetCompleteView.as_view(), name="password-reset-complete"),
    path("privacy/", views.legal_page, {"page": "privacy"}, name="privacy"),
    path("terms/", views.legal_page, {"page": "terms"}, name="terms"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/<slug:section>/", views.dashboard, name="dashboard-section"),
    path("dashboard/clients/create/", views.client_create, name="client-create"),
    path("dashboard/clients/<uuid:pk>/update/", views.client_update, name="client-update"),
    path("dashboard/clients/<uuid:pk>/invite/", views.client_create_invite, name="client-invite-create"),
    path("dashboard/clients/<uuid:pk>/revoke/", views.client_revoke_access, name="client-revoke"),
    path("dashboard/leads/<uuid:pk>/convert-client/", views.lead_convert_client, name="lead-convert-client"),
    path("dashboard/tasks/create/", views.task_create, name="task-create"),
    path("dashboard/tasks/<uuid:pk>/update/", views.task_update, name="task-update"),
    path("team/tasks/<uuid:pk>/update/", views.task_update, name="team-task-update"),
    path("team/tasks/<uuid:pk>/status/", views.task_set_status, name="team-task-status"),
    path("dashboard/tasks/<uuid:pk>/status/", views.task_set_status, name="task-status"),
    path("dashboard/calendar/day/", views.calendar_day_update, name="calendar-day-update"),
    path("dashboard/calendar/weekly/", views.weekly_schedule_update, name="weekly-schedule-update"),
    path("dashboard/calendar/employee-day/", views.employee_day_schedule_update, name="employee-day-schedule-update"),
    path("dashboard/calendar/create/", views.schedule_create, name="schedule-create"),
    path("dashboard/calendar/<uuid:pk>/update/", views.schedule_update, name="schedule-update"),
    path("dashboard/calendar/<uuid:pk>/delete/", views.schedule_delete, name="schedule-delete"),
    path("dashboard/time/clock/", views.time_clock, name="time-clock"),
    path("team/time/clock/", views.time_clock, name="team-time-clock"),
    path("dashboard/time/<uuid:pk>/update/", views.time_update, name="time-update"),
    path("team/time/<uuid:pk>/update/", views.time_update, name="team-time-update"),
    path("dashboard/documents/upload/", views.document_upload, name="document-upload"),
    path("dashboard/messages/<uuid:pk>/read/", views.staff_mark_message_read, name="staff-message-read"),
    path("dashboard/clients/<uuid:client_pk>/messages/reply/", views.staff_message_reply, name="staff-message-reply"),
    path("dashboard/notifications/<uuid:pk>/read/", views.dashboard_notification_mark_read, name="dashboard-notification-mark-read"),
    path("dashboard/notifications/read-all/", views.dashboard_notifications_mark_all_read, name="dashboard-notifications-mark-all-read"),
    path("dashboard/team/invite/", views.employee_invite_create, name="employee-invite-create"),
    path("dashboard/team/<int:pk>/profile/", views.employee_profile_update, name="employee-profile-update"),
    path("team/profile/<int:pk>/", views.employee_profile_update, name="team-profile-update"),
    path("team/notifications/devices/", views.notification_device_register, name="notification-device-register"),
    path("team/notifications/devices/deactivate/", views.notification_device_deactivate, name="notification-device-deactivate"),
    path("team/notifications/<uuid:pk>/read/", views.employee_notification_mark_read, name="notification-mark-read"),
    path("team/notifications/read-all/", views.employee_notifications_mark_all_read, name="notifications-mark-all-read"),
    path("team/notifications/", views.employee_notifications, name="team-notifications"),
    path("team/clients/<uuid:client_pk>/messages/reply/", views.staff_message_reply, name="team-staff-message-reply"),
    path("dashboard/team/<int:pk>/reset/", views.employee_password_reset_create, name="employee-reset-create"),
    path("dashboard/leads/create/", views.lead_create, name="lead-create"),
    path("dashboard/leads/delete-all/", views.lead_delete_all, name="lead-delete-all"),
    path("dashboard/leads/<uuid:pk>/delete/", views.lead_delete, name="lead-delete"),
    path("dashboard/leads/<uuid:pk>/restore/", views.lead_restore, name="lead-restore"),
    path("dashboard/leads/<uuid:pk>/status/", views.lead_update_status, name="lead-status"),
    path("dashboard/leads/<uuid:pk>/assign/", views.lead_assign, name="lead-assign"),
    path("dashboard/leads/<uuid:pk>/priority/", views.lead_toggle_priority, name="lead-priority"),
    path("dashboard/leads/<uuid:pk>/note/", views.lead_update_note, name="lead-note"),
    path("dashboard/leads/<uuid:pk>/follow-up/", views.lead_create_followup, name="lead-followup"),
    path("dashboard/leads/attachments/<uuid:pk>/", views.lead_attachment_file, name="lead-attachment-file"),
    path("dashboard/estimates/create/", views.estimate_create, name="estimate-create"),
    path("dashboard/estimates/<uuid:pk>/update/", views.estimate_update, name="estimate-update"),
    path("dashboard/estimates/<uuid:pk>/send/", views.estimate_send, name="estimate-send"),
    path("dashboard/estimates/<uuid:pk>/create-project/", views.estimate_create_project, name="estimate-project"),
    path("dashboard/projects/create/", views.project_create, name="project-create"),
    path("dashboard/projects/<uuid:pk>/update/", views.project_update, name="project-update"),
    path("dashboard/projects/<uuid:pk>/invite/", views.project_create_invite, name="project-invite"),
    path("dashboard/projects/<uuid:pk>/update-note/", views.project_add_update, name="project-add-update"),
    path("dashboard/milestones/<uuid:pk>/toggle/", views.milestone_toggle, name="milestone-toggle"),
    path("dashboard/media/upload/", views.media_upload, name="media-upload"),
    path("dashboard/media/<uuid:pk>/update/", views.media_edit, name="media-update"),
    path("team/media/upload/", views.media_upload, name="team-media-upload"),
    path("team/media/<uuid:pk>/update/", views.media_edit, name="team-media-update"),
    path("team/projects/<uuid:pk>/update-note/", views.project_add_update, name="team-project-add-update"),
    path("dashboard/content/update/", views.content_update, name="content-update"),
    path("portal/", views.portal, name="portal"),
    path("portal/estimates/<uuid:pk>/accept/", views.portal_accept_estimate, name="portal-accept-estimate"),
    path("portal/estimates/<uuid:pk>/decline/", views.portal_decline_estimate, name="portal-decline-estimate"),
    path("portal/notifications/<uuid:pk>/read/", views.client_notification_mark_read, name="client-notification-mark-read"),
    path("portal/notifications/read-all/", views.client_notifications_mark_all_read, name="client-notifications-mark-all-read"),
    path("portal/messages/create/", views.portal_send_message, name="portal-message"),
    path("accounts/invite/employee/<str:token>/", views.employee_invite, name="employee-invite"),
    path("accounts/invite/<str:token>/", views.client_invite, name="client-invite"),
    path("team/", views.team, name="team"),
    path("team/<slug:section>/", views.team, name="team-section"),
    path("projects/<uuid:pk>/", views.public_project_detail, name="project-detail"),
    path("project-covers/<uuid:pk>/", views.project_cover_file, name="project-cover"),
    path("documents/<uuid:pk>/", views.document_file, name="document-file"),
    path("media/<uuid:pk>/", views.media_file, name="media-file"),
    # Compatibility aliases for links created during the initial prototype.
    path("demo/admin/", views.legacy_dashboard, name="legacy-admin"),
    path("demo/admin/<slug:section>/", views.legacy_dashboard, name="legacy-admin-section"),
    path("demo/portal/", views.legacy_portal, name="legacy-portal"),
]
