# Generated by Django 6.1 on 2026-08-31

from django.db import migrations, models

import operations.models
import operations.storage


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_adminsecurityprofile_adminrecoverytoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadattachment",
            name="file",
            field=models.FileField(
                storage=operations.storage.ContactSubmissionStorage,
                upload_to="contact-form/%Y/%m/",
                validators=[operations.models.validate_uploaded_media],
            ),
        ),
    ]
