# Generated by Django 6.1 on 2026-08-31

import operations.models
import operations.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0005_alter_leadattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadattachment",
            name="file",
            field=models.FileField(
                storage=operations.storage.ContactSubmissionStorage,
                upload_to="contact-form/%Y/%m/",
                validators=[operations.models.validate_contact_upload],
            ),
        ),
    ]
