# Generated by Django 5.2.5 on 2026-09-04 03:56

import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_construction_idempotency_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='signed_pdf',
            field=models.FileField(blank=True, upload_to='projects/agreements/%Y/%m/', validators=[operations.models.validate_signed_pdf]),
        ),
        migrations.AlterField(
            model_name='costentry',
            name='receipt',
            field=models.FileField(blank=True, upload_to='projects/receipts/%Y/%m/', validators=[operations.models.validate_construction_document]),
        ),
    ]
