# Generated by Django 5.2.5 on 2026-09-04 04:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_sitevisit_idempotency_key_alter_agreement_signed_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CloseoutItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('final_inspection', 'Final inspection'), ('punch_list', 'Punch list'), ('documents', 'Closeout documents'), ('warranty', 'Warranty'), ('client_walkthrough', 'Client walkthrough'), ('final_invoice', 'Final invoice'), ('other', 'Other')], default='other', max_length=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('complete', 'Complete'), ('blocked', 'Blocked'), ('not_applicable', 'Not applicable')], default='open', max_length=16)),
                ('required', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_closeout_items', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_closeout_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closeout_items', to='operations.project')),
            ],
            options={
                'ordering': ['status', 'category', 'label'],
                'constraints': [models.UniqueConstraint(fields=('project', 'key'), name='unique_project_closeout_key')],
            },
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=14)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_construction_problems', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to='operations.project')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_construction_problems', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_construction_problems', to=settings.AUTH_USER_MODEL)),
                ('supporting_media', models.ManyToManyField(blank=True, related_name='problem_reports', to='operations.mediaasset')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reports', to='operations.task')),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='operations__project_0bc910_idx'), models.Index(fields=['severity', 'status'], name='operations__severit_ed13ac_idx')],
            },
        ),
    ]
