# Generated by Django 5.2.5 on 2026-09-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_lead_idempotency_key_permit_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='costentry',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
