# Generated by Django 5.2.5 on 2026-09-05 02:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_commitment_idempotency_key_costentry_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorder',
            name='supporting_media',
            field=models.ManyToManyField(blank=True, related_name='change_orders', to='operations.mediaasset'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='media_assets',
            field=models.ManyToManyField(blank=True, related_name='daily_reports', to='operations.mediaasset'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='context',
            field=models.CharField(choices=[('progress', 'Progress'), ('existing_condition', 'Existing condition'), ('site_visit', 'Site visit'), ('daily_report', 'Daily report'), ('problem_report', 'Problem report'), ('change_order', 'Change order')], default='progress', max_length=24),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='site_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='operations.sitevisit'),
        ),
        migrations.CreateModel(
            name='NativeUploadGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('target', models.CharField(choices=[('project_media', 'Project media'), ('project_document', 'Project document'), ('site_visit_media', 'Site visit media'), ('daily_report_media', 'Daily report media'), ('problem_media', 'Problem report media'), ('change_order_media', 'Change order media'), ('existing_condition', 'Existing condition')], max_length=32)),
                ('target_object_id', models.CharField(blank=True, max_length=64)),
                ('visibility', models.CharField(default='internal', max_length=20)),
                ('context', models.CharField(default='progress', max_length=24)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='native_upload_grants', to=settings.AUTH_USER_MODEL)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_upload_grants', to='operations.mediaasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_upload_grants', to='operations.project')),
                ('project_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_upload_grants', to='operations.projectdocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'expires_at'], name='operations__actor_i_4129bf_idx'), models.Index(fields=['project', 'target', 'expires_at'], name='operations__project_715a5b_idx')],
            },
        ),
    ]
