# Generated by Django 5.2.5 on 2026-09-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0018_native_upload_capabilities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="joist_client_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="estimate",
            name="joist_deposit_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="joist_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="estimate",
            name="joist_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("sent", "Sent"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="not_started",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="joist_status_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="joist_status_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_joist_estimate_statuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="estimate",
            name="joist_status_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="joist_total",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="joist_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="joist_client_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="joist_invoice_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="joist_invoice_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("sent", "Sent"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                ],
                default="not_started",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="joist_invoice_status_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="joist_invoice_status_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_joist_invoice_statuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="joist_invoice_status_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="joist_invoice_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
