from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0019_joist_status_layer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estimate",
            old_name="joist_url",
            new_name="external_url",
        ),
        migrations.RenameField(
            model_name="estimate",
            old_name="joist_reference",
            new_name="external_reference",
        ),
        migrations.RenameField(
            model_name="estimate",
            old_name="joist_total",
            new_name="external_total",
        ),
        migrations.RenameField(
            model_name="estimate",
            old_name="joist_deposit_amount",
            new_name="external_deposit_amount",
        ),
        migrations.RenameField(
            model_name="estimate",
            old_name="joist_status",
            new_name="external_status",
        ),
        migrations.RenameField(
            model_name="estimate",
            old_name="joist_status_at",
            new_name="external_status_at",
        ),
        migrations.RenameField(
            model_name="estimate",
            old_name="joist_status_by",
            new_name="external_status_by",
        ),
        migrations.RenameField(
            model_name="estimate",
            old_name="joist_status_note",
            new_name="external_status_note",
        ),
        migrations.RenameField(
            model_name="estimate",
            old_name="joist_client_visible",
            new_name="external_client_visible",
        ),
        migrations.RenameField(
            model_name="paymentschedule",
            old_name="joist_invoice_url",
            new_name="external_invoice_url",
        ),
        migrations.RenameField(
            model_name="paymentschedule",
            old_name="joist_invoice_reference",
            new_name="external_invoice_reference",
        ),
        migrations.RenameField(
            model_name="paymentschedule",
            old_name="joist_invoice_status",
            new_name="external_invoice_status",
        ),
        migrations.RenameField(
            model_name="paymentschedule",
            old_name="joist_invoice_status_at",
            new_name="external_invoice_status_at",
        ),
        migrations.RenameField(
            model_name="paymentschedule",
            old_name="joist_invoice_status_by",
            new_name="external_invoice_status_by",
        ),
        migrations.RenameField(
            model_name="paymentschedule",
            old_name="joist_invoice_status_note",
            new_name="external_invoice_status_note",
        ),
        migrations.RenameField(
            model_name="paymentschedule",
            old_name="joist_client_visible",
            new_name="external_client_visible",
        ),
    ]
