# Generated by Django 6.1 on 2026-09-08 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_provider_neutral_external_estimate_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='external_status_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_external_estimate_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='external_invoice_status_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_external_invoice_statuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
