# Generated by Django 6.1 on 2026-09-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_client_push_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_places_display_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_places_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_places_review_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_reviews_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_review_id', models.CharField(max_length=512, unique=True)),
                ('place_id', models.CharField(max_length=255)),
                ('author_name', models.CharField(default='Google user', max_length=180)),
                ('author_uri', models.URLField(blank=True, max_length=1000)),
                ('author_photo_uri', models.URLField(blank=True, max_length=2000)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_text', models.TextField(blank=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('google_maps_uri', models.URLField(blank=True, max_length=2000)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-publish_time', 'pk'],
                'indexes': [models.Index(fields=['place_id', 'display_order'], name='operations__place_i_d62cba_idx')],
            },
        ),
    ]
